name: CI/CD Workflow

on: 
  push:
  # Run by default on all the branches. Deploy job will run on main only, due to condition
  # This enables creating tagged docker images in GHCR for each branch without deploying them
  # To change this behavior and builkd for main only, replace the asterisks with main
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
      REF_NAME: ${{ github.ref_name }}
      RUN_NUMBER: ${{ github.run_number }}
    
    steps:
    - name: 🤝 Checkout Code
      uses: actions/checkout@v4
      
    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🔑 Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    #For DockerHub (set proper env values above)
    #- name: Login to DockerHub
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_TOKEN }}

    - name: 🚢 Build and push tagged only
      id: docker_build
      if: github.ref != 'refs/heads/main' # This step runs on non-main branches
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.REF_NAME }}-${{ env.RUN_NUMBER }}
        
    - name: 🎁 Build and push tagged and latest
      id: docker_build_latest
      if: github.ref == 'refs/heads/main' # This step runs on main branch only
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.REF_NAME }}-${{ env.RUN_NUMBER }}
          ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main' # This condition ensures that deploy job runs only for main branch
    runs-on: ubuntu-latest
    
    steps:
    - name: 🤝 Checkout Code
      uses: actions/checkout@v4
      with:
        ref: main # Checkout only relevant branch

    # Remove unnecessary git and github folders before copying files to VM
    - name: 🚮 Remove git and github folders
      run: |
        rm -rf .git .github 

    - name: 📤 Copy files to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "." # Copy all the files to the VM
        target: ${{github.event.repository.name}}
        overwrite: true

    - name: 🚀 Deploy to AWS VM
      uses: appleboy/ssh-action@v1.0.0
      env:
        DIRECTORY: ${{github.event.repository.name}}
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DIRECTORY
        script: |
          cd ~/$DIRECTORY
          docker compose pull
          docker compose up -d
